version: '3.8'
services:
    app:
        build:
           context: .
           dockerfile: _docker/app/DockerFile
        container_name: shop_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - laravel_network
        env_file:
            - .env

    db:
        image: mariadb:10.5
        container_name: shop_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop_bd
        ports:
            - "3306:3306"
        networks:
            - laravel_network
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
            - ./tmp/db:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: shop_redis
        restart: always
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: shop_nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

volumes:
    dbdata:

networks:
    laravel_network:
        driver: bridge
